export enum REPOSITORY_INJECTION_TOKEN {
  YOUTUBE_REPOSITORY = 'YOUTUBE_REPOSITORY',
  EMBEDDING_REPOSITORY = 'EMBEDDING_REPOSITORY',
  DOCUMENT_REPOSITORY = 'DOCUMENT_REPOSITORY',
  DOCUMENT_SEGMENT_REPOSITORY = 'DOCUMENT_SEGMENT_REPOSITORY',
  FLASH_CARD_REPOSITORY = 'FLASH_CARD_REPOSITORY',
  USER_REPOSITORY = 'USER_REPOSITORY',
  DATASET_REPOSITORY = 'DATASET_REPOSITORY',
  DATASET_DOCUMENT_JOIN_REPOSITORY = 'DATASET_DOCUMENT_JOIN_REPOSITORY',
  CHAPTER_REPOSITORY = 'CHAPTER_REPOSITORY',
}
